(define (k0 v e)
  (display v))
(define (fact n k fact-e k-e)
  (define (k1 v e)
    (define n (vector-ref e 0))
    (define k (vector-ref e 1))
    (define k-e (vector-ref e 3))
    (k (* v n) k-e))
  (define fact (vector-ref fact-e 1))
  (define k1-e (vector n k fact-e k-e k1 fact))
  (if (<= n 2)
    (k n k-e)
    (fact (- n 1) k1 fact-e k1-e)))
(define fact-e0 (vector k0 fact))
(define k-e0 fact-e0)
(fact 5 k0 fact-e0 k-e0)
